-- Create database for the laptop pipeline project
CREATE DATABASE LAPTOP_PIPELINE_DB;

-- Create schemas representing Medallion layers
CREATE SCHEMA LAPTOP_PIPELINE_DB.BRONZE;
CREATE SCHEMA LAPTOP_PIPELINE_DB.SILVER;
CREATE SCHEMA LAPTOP_PIPELINE_DB.GOLD;

-- Use your project database and Silver schema
USE DATABASE LAPTOP_PIPELINE_DB;
USE SCHEMA SILVER;


-- Landing table for cleaned/enriched data coming from BigQuery
CREATE OR REPLACE TABLE VALID_LAPTOPS_ENRICHED (
  NAME STRING,
  DISCOUNTED_PRICE FLOAT,
  ACTUAL_PRICE FLOAT,
  SAVING_PERCENT INTEGER,
  RATING FLOAT,
  REVIEWS INTEGER,
  BRAND STRING,
  MODEL STRING,
  CORE STRING,
  SSD STRING,
  SSD_GB INTEGER,
  HAS_VALID_SSD INTEGER
);


SELECT
  *
FROM
  "LAPTOP_PIPELINE_DB"."SILVER"."VALID_LAPTOPS_ENRICHED"
LIMIT
  10;


-- Switch to the GOLD schema
USE DATABASE LAPTOP_PIPELINE_DB;
USE SCHEMA GOLD;

-- Create an analyst-ready table with useful pricing insights
CREATE OR REPLACE TABLE LAPTOP_PRICE_ANALYTICS AS
SELECT
    BRAND,
    MODEL,
    SSD_GB,
    CORE,
    RATING,
    REVIEWS,
    DISCOUNTED_PRICE,
    ACTUAL_PRICE,
    SAVING_PERCENT
FROM LAPTOP_PIPELINE_DB.SILVER.VALID_LAPTOPS_ENRICHED
WHERE HAS_VALID_SSD = 1;

-- Top rated laptops
SELECT *
FROM GOLD.LAPTOP_PRICE_ANALYTICS
ORDER BY RATING DESC
LIMIT 10;


-- Laptops with highest discount (best value)
SELECT *
FROM GOLD.LAPTOP_PRICE_ANALYTICS
ORDER BY SAVING_PERCENT DESC
LIMIT 10;


-- Average discounted price by brand
SELECT
    BRAND,
    AVG(DISCOUNTED_PRICE) AS AVG_PRICE
FROM GOLD.LAPTOP_PRICE_ANALYTICS
GROUP BY BRAND
ORDER BY AVG_PRICE DESC;

-- Check how many records exist in the Gold analytics table
SELECT COUNT(*)
FROM GOLD.LAPTOP_PRICE_ANALYTICS;

-- Preview first 10 rows from the Gold layer
SELECT *
FROM GOLD.LAPTOP_PRICE_ANALYTICS
LIMIT 10;

-- Brand-level analytics summary
CREATE OR REPLACE TABLE GOLD.BRAND_PRICE_ANALYSIS AS
SELECT
    BRAND,
    COUNT(*) AS TOTAL_MODELS,
    AVG(DISCOUNTED_PRICE) AS AVG_PRICE,
    MAX(RATING) AS TOP_RATING
FROM SILVER.VALID_LAPTOPS_ENRICHED
GROUP BY BRAND;

